### ISSUE TITLE
warn users on use of same Coord objects on distinct datasets 

### ISSUE THREAD

**Issue by atravert** [spectrochempy/spectrochempy#310]
As shown below, setting coordset with assignment:
`D.set_coordset(y=ycoord, x=xcoord)`
changes the names of the Coord object (it will be set to y and x for yccord and xcoord, respectively

but this can lead to bugs if the same Coord objects are used as coordinates of other dataset with other name

```
import spectrochempy as scp
import numpy as np

D = scp.NDDataset(np.zeros((10, 5)))
c5 = scp.Coord.linspace(start=0., stop=1000., num=5, name='xcoord')
c10 = scp.Coord.linspace(start=0., stop=1000., num=10, name='ycoord')

print(c5.name)   # as expected: "xcoord"
D.set_coordset(y=c10, x=c5)
print(c5.name)   # now it is "x"
print(D.coordset)   # as expected: "CoordSet: [x:<untitled>, y:<untitled>]"
print(D.dims)    # as expected: ['y', 'x']


E = scp.NDDataset(np.ndarray((5, 10)))
E.set_coordset(s=c5, t=c10)

print(D.coordset) # now the Coord names of D have been changed: "CoordSet: [s:<untitled>, t:<untitled>]"
print(D.dims)   #but not the dim names: ['y', 'x'], and this can lead to bugs:

print(D[:,1]) # ERROR | ValueError: the size of a coordinates array must be None or be equal to that of the respective `y` data dimension but coordinate size=5 != data shape[0]=10

```
this problem can be avoided if copies of the coord are used, e.g.
 
`E.set_coordset(s=c5.copy(), t=c10.copy)`

**Comment by atravert** [comment]
PS: maybe add a check of the compatibility of NDDatase.dims with coord names when a new assignment is made, or change the value of dims accordingly ?

**Comment by fernandezc** [comment]
Indeed when we create a CoordSet from Coord objects, there was no copy of the objects by default.

That's why the solution was:

`E.set_coordset(s=c5.copy(), t=c10.copy) `

This behavior has been changed in the new version - by default Coord objects are now copied.

To change this behavior and get the previous situation, you have to pass the parameter 'copy=False' to the CoordSet:

`E.set_coordset(s=c5, t=c10, copy=False)  `

--
Remark, as indicated in the doc, when you want to change the default names x, y ... for example for s,t, you have to specify the names of the dimensions and their order before creating the CoordSet. Indeed, the order of the coordinates is not known without this:

```
E.dims = ["s", "t"]
E.set_coordset(s=c5, t=c10)
```

see [Setting-coordinates-using-set_coordset](https://www.spectrochempy.fr/latest/userguide/dataset/dataset.html#Setting-coordinates-using-set_coordset)
