### ISSUE TITLE
[Bug] plot_multiple spectra

### ISSUE THREAD

**Issue by fernandezc** [spectrochempy/spectrochempy#690]
### Discussed in https://github.com/spectrochempy/spectrochempy/discussions/689

> For some reason, I get this error: | TypeError: spectrochempy.core.dataset.arraymixins.ndplot.NDPlot.plot() got multiple values for keyword argument 'ls' for B5. I tried linestyle = '-' and that worked though!

**Comment by fernandezc** [comment]
Hello @sabourizk

Please can you provide a minimal example of your problem, because I can't reproduce it with the latest dev version.

Thanks.

**Comment by sabourizk** [comment]
I used the same code as recommended in #689 (the file called lasertest is the one I used in the code). This worked, but using ls instead of linestyle came up with this error :  ERROR | TypeError: spectrochempy.core.dataset.arraymixins.ndplot.NDPlot.plot() got multiple values for keyword argument 'ls'

prefs = B5.preferences
prefs.figure.figsize = (8,6) 
datasets = list(B5)
_ = scp.plot_multiple(datasets, 
                      method="pen",
                      legend="best",
                      labels=["A", "B"],
                      linestyle='-',  # solid line
                      shift=1000, # vertical shift
                     )

**Comment by fernandezc** [comment]
Ok it's a bug in version 0.6.5, but it's been fixed since 0.6.6.  Maybe you can update. 
In any case, thanks for helping us improve the program's stability. All contributions, questions, bug reports are very beneficial to us.

Also, if you're using LabSpec software, I'm interested in any feedback on the reader, especially if something isn't implemented (which is probably the case with many of them). I don't have direct access to the software. So do not hesitate to ask if something doesn't work.
