### ISSUE TITLE
[Bug]: The 2D plots have a symmetric colorbar (zmax, -zmax).

### ISSUE THREAD

**Issue by Juliogallinaro** [spectrochempy/spectrochempy#728]
### What happened?

The 2D plots have a symmetric colorbar (zmax, -zmax).

### What did you expect to happen?

The 2D plots have a symmetric colorbar (zmax, -zmax) due to lines 380 and 381 in the script spectrochempy/spectrochempy/core/plotters/plot2d.py. Removing these lines will allow the plots to have a more appropriate colorbar. The figures below show the current (symmetric) colorbar and the colorbar after removing the lines.
![1](https://github.com/spectrochempy/spectrochempy/assets/1587466/3b272078-09af-4524-a55c-54ed2ebf077f)
![2](https://github.com/spectrochempy/spectrochempy/assets/1587466/20ba1635-d855-4ad1-9924-b605dca20826)

### Environment

INSTALLED VERSIONS
------------------
commit: None
python: 3.10.0rc2 (tags/v3.10.0rc2:839d789, Sep  7 2021, 18:51:45) [MSC v.1929 64 bit (AMD64)]
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: AMD64 Family 23 Model 1 Stepping 1, AuthenticAMD
byteorder: little
LC_ALL: None
LANG: None
LOCALE: ('en_US', 'ISO8859-1')

 -- dev installation --

**Comment by fernandezc** [comment]
Hi @Juliogallinaro: In fact, this is done deliberately, because in many applications, it's quite interesting to have a coherent color code for positive and negative values. But I admit that in your case, if the values are always positive, it's worth making the proposed change. It could certainly be an option in either direction. Unfortunately, I don't have much time at the moment to work on it, but I'll look into it occasionally. Perhaps if you have the courage and inclination, you could propose a Pull Request yourself, but if not, I'll take care of it in a while. 
Best regards

**Comment by fernandezc** [comment]
So it's not really a bug. I changed the label to 'enhancement'.

**Comment by atravert** [comment]
Hello @Juliogallinaro: now the colormap normalization for `surface`, `image` and `map` plot methods has been changed for consistency with matplotlib default and behaves as you suggested. Note that the former behaviour can be obtained
by passing a `norm` parameter to the `plot` method (see userguide/plotting).
Thank you very much for this suggestion.
